
import {
  LayoutDashboard,
  Calendar,
  Music,
  Users,
  MessageSquare,
  BarChart3,
  Settings,
  LogOut,
  ChevronLeft,
  ChevronRight,
  PlusCircle,
  MoreVertical,
  User,
  Clock,
  BookOpen,
  LogIn,
  Sun,
  Moon,
  Home,
  Guitar,
  Lightbulb,
  Loader2,
  Send,
  UserPlus,
  BarChart,
  ClipboardList,
  Check,
  CalendarDays
} from 'lucide-react';

export const Icons = {
  dashboard: LayoutDashboard,
  lessons: Calendar,
  practice: Music,
  students: Users,
  instructors: UserPlus,
  community: MessageSquare,
  analytics: BarChart3,
  settings: Settings,
  logout: LogOut,
  login: LogIn,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  add: PlusCircle,
  more: MoreVertical,
  user: User,
  clock: Clock,
  book: BookOpen,
  sun: Sun,
  moon: Moon,
  home: Home,
  guitar: Guitar,
  idea: Lightbulb,
  spinner: Loader2,
  send: Send,
  barchart: BarChart,
  clipboard: ClipboardList,
  check: Check,
  calendar: CalendarDays,
};
